version: '3.8'

services:
  backend:
    build: ./server
    ports:
      - "5000:5000"
    environment:
      - MONGODB_URI=mongodb+srv://admin:123@cluster0.hxmnzcv.mongodb.net/cloud_lab?appName=Cluster0
    networks:
      - mern-net

  frontend:
    build: ./client
    ports:
      - "5173:5173"
    depends_on:
      - backend
    networks:
      - mern-net

networks:
  mern-net:
    driver: bridge