version: '3.8'

services:
  backend:
    image: takiet12012005/mern-backend:1.0
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - MONGODB_URI=mongodb+srv://admin:123@cluster0.hxmnzcv.mongodb.net/cloud_lab?retryWrites=true&w=majority
    networks:
      - mern-net

  frontend:
    image: takiet12012005/mern-frontend:1.0
    ports:
      - "5173:5173"
    depends_on:
      - backend
    networks:
      - mern-net

networks:
  mern-net:
    driver: bridge