version: '3.8'

services:
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=123
    networks:
      - mern-net

  backend:
    image: takiet12012005/mern-backend:1.0
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - MONGODB_URI=mongodb://admin:123@mongo:27017/cloud_lab?authSource=admin
    depends_on:
      - mongo
    networks:
      - mern-net

  frontend:
    image: takiet12012005/mern-frontend:1.0
    ports:
      - "5173:5173"
    depends_on:
      - backend
    networks:
      - mern-net

networks:
  mern-net:
    driver: bridge
